### ISSUE TITLE
Improve getTemplates function to search for templates by name

### ISSUE THREAD

**Issue by magicdude4eva** [twisted1919/mailwizz-php-sdk#14]
Hi there,

is it possible to extend method https://github.com/twisted1919/mailwizz-php-sdk/blob/master/MailWizzApi/Endpoint/Templates.php#L30 so that we can pass in a template name and it then does a partial match/return of results (same as what the front end does).

**Comment by twisted1919** [comment]
Hmm... maybe better add a new method, like `searchTemplates()` ?

**Comment by magicdude4eva** [comment]
Whatever is easier for you. `searchTemplates()` would also work - I would just need to be able to narrow down the result-set and have pagination.

**Comment by twisted1919** [comment]
See https://github.com/twisted1919/mailwizz-php-sdk/commit/add5c99378b8e7c591a0eee33bca81cab38aad0a

Closing this.
