### ISSUE TITLE
How to disable confirmation email sent to subscribers when added to a list

### ISSUE THREAD

**Issue by ghost** [twisted1919/mailwizz-php-sdk#17]
How can I disable the confirmation email that gets sent to subscribers when they get added to a list?  I don't see any examples of how to set it to single opt-in or anything that would accomplish this.

**Comment by twisted1919** [comment]
You do this from mailwizz itself, by editing your list and setting the list opt-in process to single opt-in.

**Comment by ghost** [comment]
But I am creating the list via the SDK then adding subscribers via the SDK immediately afterwards......

**Comment by twisted1919** [comment]
Did you set the `opt_in` property for the `general` to `single` ?

Example at https://github.com/twisted1919/mailwizz-php-sdk/blob/master/examples/lists_create.php#L22
