### ISSUE TITLE
how to create bulk subscribers using mailwizz php sdk

### ISSUE THREAD

**Issue by rameshwebmaster** [twisted1919/mailwizz-php-sdk#18]
hello,
when i create audience and while creating around 700-800 subscribers, it is taking time like 10-15min. so i want to create bulk subscribers because we have more than 10k subscribers and so want to reduce the time on server.
is that possible using php sdk?

Thanks in Advance.

**Comment by twisted1919** [comment]
Anytime when you want to push huge amounts of data over http you don;t do it from the browser but from the command line, so implement some sort of queue that takes the subscribers from the web interface and puts them in the queue which you later process and send to mailwizz.

**Comment by rameshwebmaster** [comment]
I am already using queue for creating multiple subscribers. i thought there might be any other method to create same so we can reduce the processing time.
Thanks
