### ISSUE TITLE
what is URL Hash in tracking campaign ?

### ISSUE THREAD

**Issue by rameshwebmaster** [twisted1919/mailwizz-php-sdk#19]
hello ,
i want to track campaign and i have got following code
// Track subscriber click for campaign click
$response = $endpoint->trackUrl('CAMPAIGN-UNIQUE-ID', 'SUBSCRIBER-UNIQUE-ID', 'URL-HASH');
what is URL-Hash field and what value should i pass for same?

**Comment by twisted1919** [comment]
It's the `sha1` of the url from the email template that you want to track. Look in the `campaign_url` table to see the hashes mailwizz creates when preparing a campaign.

**Comment by rameshwebmaster** [comment]
so you mean to say value of URL-HASH will be 'sha1'  right?

**Comment by twisted1919** [comment]
That is correct yes.
