### ISSUE TITLE
Custom Field creation in Lists

### ISSUE THREAD

**Issue by vishnurs** [twisted1919/mailwizz-php-sdk#2]
I couldn't find an example to create custom lists fields. If there is any, please let me know.

Thanks.

**Comment by twisted1919** [comment]
That's because the api isn't yet able to do this. You can implement the endpoint yourself, shouldn't be that hard.

**Comment by vishnurs** [comment]
@twisted1919  Is there any documentation available to implement custom endpoints?

**Comment by twisted1919** [comment]
Sorry but unfortunatelly no at this point. What's your issue with creating a new endpoint?Aren't the existing endpoints valid examples ?

**Comment by vishnurs** [comment]
@twisted1919 I need an option to create custom fields in lists via API. But the endpoint is not available. I have tried to create new end points but it seems to be too difficult.

**Comment by twisted1919** [comment]
@vishnurs endpoints are just controller classes, i don't see why it would be difficult given there are plenty examples. Maybe hire a php developer to help you with the implementation.
