### ISSUE TITLE
where to copy examples files 

### ISSUE THREAD

**Issue by singhk9009** [twisted1919/mailwizz-php-sdk#21]
Hello,

Was trying to use the SDK to processs bounce handling via mailwizz api 

I am just confused where to put below "exmaples" files or directory where in mailwizz installation ?

https://github.com/twisted1919/mailwizz-php-sdk/tree/master/examples

I am unable to use mailwizz api and no  where i am finding guide to setup / install 
Please guide me with steps 

I want to make my mailwizz api to work 

Thanks
Kamlesh

**Comment by minamoto19** [comment]
Hi Kamlesh,

I'm not an expert of mailwizz but I'm a programmer myself.
I think you are a bit confused.

mailwizz-php-sdk is an SDK that connects mailwizz application with your application through mailwizz API.

So you don't have to put examples folder somewhere "in mailwizz installation".
You have to copy the folder "MailWizzApi" to your application library(from where you want to connect with mailwizz) and call the SDK classes and functions wherever needed within your code.

Examples are examples. Meaning there are help files for you to adapt them in your own code.
I think you should check [campaign_bounces.php](https://github.com/twisted1919/mailwizz-php-sdk/blob/master/examples/campaign_bounces.php)

Kind regards
