### ISSUE TITLE
How to get a campaign's opens/bounces/unsubscribes via API?

### ISSUE THREAD

**Issue by huntinator7** [twisted1919/mailwizz-php-sdk#22]
Sorry for not asking this on the forums, but a third party has access to our MailWizz key, so I am unable to make an account.

I am currently implementing the API/SDK into our software, and I would like to be able to get the clicks, opens, bounces, and unsubscribes from a campaign. When using the Campaigns endpoint, it returns information such as "name", "type", "status", etc., but no opens/bounces/unsubs. CampaignsTracking allows me to get this information, but only passing in a subscriber ID, which is unhelpful because at that stage I will not know who has opened the emails. I can see the information clearly shown when I click on a certain campaign in the web panel, but cannot seem to find a way to export that data. Is there something I am missing, or is this not possible at this time? I may or may not be able to get access to the MailWizz files via SSH, so I would prefer a route that doesn't have me making my own server-side controllers.

**Comment by twisted1919** [comment]
@huntinator7 - Unfortunately stats are not available via api, you have to create your own endpoint for it.
