### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by johnabraham1** [twisted1919/mailwizz-php-sdk#24]
I followed the instructions and didn't understand the  installation part. Can I get the explanation in brief?

**Comment by twisted1919** [comment]
@johnabraham1 - Where exactly did you get stuck ?

**Comment by johnabraham1** [comment]
I've gone through the installation steps.  I downloaded the code and updated the url, public key and private key in examples/setup.php file. Then dont understand what's next step? Please help.

**Comment by twisted1919** [comment]
The setup.php file serves as an example, you have to comment the `exit` call inside it in order to actually execute the code in the example files. Once you commented out the `exit` call, access in your browser the examples, for example, the `examples/lists.php` file.

**Comment by johnabraham1** [comment]
I got this output after commenting the exit call and accessing examples/lists.php file.

`MailWizzApi_Params Object
(
    [_data:MailWizzApi_Params:private] => Array
        (
            [status] => error
            [error] => Not Found
        )

    [_readOnly:MailWizzApi_Params:private] => 
)`

**Comment by twisted1919** [comment]
From the above, it seems the url to the API is not correct, you can find the correct url in customer area, by clicking the info icon in API Keys area.

p.s: I really advise you to hire a PHP developer that has experience with using API's, we really cannot do hand-holding here.

**Comment by rajmehra9** [comment]
Hi @twisted1919 ,

I'm trying to integrate Mailwizz with 3rd party application. I've gone through the above conversation and followed the same as instructed.

I can see all the lists when I run the file called lists.php in the browser. How about copy list, delete list and create list? here I'm getting the error as "Page not found". Please suggest with the solution for this.

Thanks

**Comment by twisted1919** [comment]
You have to use the right list uid that you want to delete for example.

**Comment by rajmehra9** [comment]
I've used the uid for delete and copy. What uid should I use to create new list?

**Comment by AbdouRD** [comment]
hello, can you please show me how to install mailwizz on a fresh vps ? there was a bash command easy to install now you don't support that, can you please help ?
