### ISSUE TITLE
This email address is blacklisted

### ISSUE THREAD

**Issue by NelsonGaldeman** [twisted1919/mailwizz-php-sdk#26]
Hey, it's me bothering again. Is any other blacklist than the one under "Lists" => "Email blacklist" ? Beucase I can only see one email blacklisted and it's not the same as the ones I'm adding thought the API.

Full response

	MailWizzApi_Params Object
	(
		[_data:MailWizzApi_Params:private] => Array
			(
				[status] => error
				[error] => This email address is blacklisted.
			)

		[_readOnly:MailWizzApi_Params:private] => 
	)

**Comment by twisted1919** [comment]
Backend > Email Blacklist, that's the global blacklist, your email is there most likely.

**Comment by NelsonGaldeman** [comment]
Oh well, I only have a single account. I don't own the service but I will send an email to my provider. Thanks.
