### ISSUE TITLE
Changing Class names to customers needs

### ISSUE THREAD

**Issue by torstenlemke** [twisted1919/mailwizz-php-sdk#27]
Hey there, 

I have the extended license and wanted to change the class names (MailWizzApi_{NAME}) to something different.

I used Sublimes Replace function but it seems to break everything because it tells me:

```
MacBook-Pro:examples torstenhogel$ php lists.php

Fatal error: Uncaught Error: Class 'GoMailApi_Config' not found in /Users/torstenhogel/Library/CloudStorage/iCloud Drive/Documents/gomail-php-sdk/examples/setup.php:23
Stack trace:
#0 /Users/torstenhogel/Library/CloudStorage/iCloud Drive/Documents/gomail-php-sdk/examples/lists.php(11): require_once()
#1 {main}
  thrown in /Users/torstenhogel/Library/CloudStorage/iCloud Drive/Documents/gomail-php-sdk/examples/setup.php on line 23
```

I've also tried running cleanups via composer like cache e.g. but it didn't work.

Do you have any idea why this happens?

**Comment by twisted1919** [comment]
You have to replace the name in the source code as well, that is, the files you get when you download the library from here, all of them.

**Comment by torstenlemke** [comment]
So I have renamed **all** mailwizzapi_ to mynameapi_ that's including the whole downloaded project, if you mean those files from this repository ...

Or do you mean smth different?

**Comment by twisted1919** [comment]
That's what i meant, but also file names, ok?

**Comment by torstenlemke** [comment]
Yes I did ... thou the error says that the function doesn't exist it does ... could that be connected to an autoloader issue?

**Comment by twisted1919** [comment]
@ONIXTurtle - if you have installed from composer, you have to also modify the composer.json file in the autoload section and then recreate the composer files to autoload your class by dumping the new autoloader with `composer dump-autoload`

**Comment by torstenlemke** [comment]
It tells me the following:
Generated autoload files containing 0 classes
That's strange because it should be generating it ...

**Comment by torstenlemke** [comment]
?

**Comment by twisted1919** [comment]
Can you place the code in a repository so we can take a look? Or somewhere to download it?

**Comment by torstenlemke** [comment]
absolutely here it is: https://github.com/ONIXTurtle/gomail-php-sdk-test

**Comment by twisted1919** [comment]
Here's your issue: https://github.com/Go-On-Network/gomail-php-sdk/blob/master/composer.json#L18 most likely. 

So replace MailWizzApi_ with your naming everywhere.

**Comment by torstenlemke** [comment]
Doesn't work I'm getting the error on the rep above: https://github.com/ONIXTurtle/gomail-php-sdk-test

that it can't find the class:

MacBook-Pro:examples torstenhogel$ php countries.php

```
Fatal error: Uncaught Error: Class 'GoMailApi_Config' not found in /path/test/examples/setup.php:23
Stack trace:
#0 /path/test/examples/countries.php(11): require_once()
#1 {main}
  thrown in /path/test/examples/setup.php on line 23
```

**Comment by twisted1919** [comment]
At https://github.com/ONIXTurtle/gomail-php-sdk-test/blob/master/GoMailApi/Autoloader.php#L42 put 9 instead of 12.

**Comment by torstenlemke** [comment]
Awesome that fixed it ;)
