### ISSUE TITLE
Add to email blacklist?

### ISSUE THREAD

**Issue by brianchance** [twisted1919/mailwizz-php-sdk#28]
Is there any way to add an email to the email blacklist? Does unsubscribeByEmailFromAllLists add that email to the blacklist or just unsubscribe to all currently subscribed lists?

**Comment by twisted1919** [comment]
There is no endpoint to add to the blacklist as this affects all customers in a single instance, so you can't have customer a blacklist 10 emails which are also part of customer b and c. 

You can write your own endpoint to do this if you wish, it should be simple enough.
