### ISSUE TITLE
PHP 7.4 issues

### ISSUE THREAD

**Issue by cwuensche** [twisted1919/mailwizz-php-sdk#33]
You have many instances where you're accessing the array using curly braces.

Fix: Replace the {} with [] when you're accessing array elements.
https://github.com/twisted1919/mailwizz-php-sdk/blob/cb8616026bb26c9233ad8232b908516ac993ac6e/MailWizzApi/Json.php#L166

**Comment by twisted1919** [comment]
Thanks for pointing out, i'll leave this open to check for more occurrences tomorrow when at work. 
If you find anything else, let me know.

**Comment by twisted1919** [comment]
I think this has been taken care of in 1.0.7. We added phpstan for checking and also started adding tests, hopefully will catch such things in future.
