### ISSUE TITLE
Get Subscriber ID

### ISSUE THREAD

**Issue by ryscript** [twisted1919/mailwizz-php-sdk#5]
Hi,

Is it possible to get Subscriber ID returned on "create" endpoint? I tried dumping returned data and I can't seem to find in there, any solution where I can get Subscriber ID?

The idea is I wanted to get subscriber ID on newly added user.

Thanks

**Comment by twisted1919** [comment]
@ryscript - makes sense, i've added it in the code.
You can open apps/api/controllers/List_subscribersControllers.php and in both actionCreate/actionUpdate, return the data like:

``` php
return $this->renderJson(array(
            'status' => 'success',
           'data'   => array('record' => $subscriber->getAttributes(array('subscriber_uid', 'email', 'ip_address', 'source'))),
        ), 200);
```

**Comment by ryscript** [comment]
Hi @twisted1919 thanks for the quick reply appreciate it, okay I'll try this out and let you know asap.

Thanks

**Comment by ryscript** [comment]
Yes it works perfectly now, thanks
