### ISSUE TITLE
Method to Terminate Customer Account

### ISSUE THREAD

**Issue by gonzad26** [twisted1919/mailwizz-php-sdk#6]
Hi, i'm developing a module to integrate our crm with mailwizz and i successfully integrate de create customer function. 
Is it possibly to add a function to terminate an account with the email address using the API.
Thanks

**Comment by twisted1919** [comment]
> Is it possibly to add a function to terminate an account with the email address using the API.

Not really, think that the api is accessible by anyone that has a customer key, so an endpoint that would terminate an account should be created separately to avoid allowing customers doing nasty things.

Just create a separate endpoint for this with a static access key and that's it.

**Comment by gonzad26** [comment]
I have done that, I've created a special endpoint to create customers only but now I need a function to terminate accounts.
After this, how I continue? Codding a function in subscriber controller?
Thanks

**Comment by twisted1919** [comment]
> After this, how I continue? Codding a function in subscriber controller?  

Nope, just create a separate controller altogether ;)
