### ISSUE TITLE
Insecure use of libcurl / HTTPS

### ISSUE THREAD

**Issue by notr1ch** [twisted1919/mailwizz-php-sdk#7]
https://github.com/twisted1919/mailwizz-php-sdk/blob/master/MailWizzApi/Http/Request.php#L126

The application seems to purposefully break HTTPS by disabling certificate verification - validating the certificate is critical to guarantee the security of HTTPS. Given that trusted certificates are freely obtainable from Let's Encrypt, adding this as a workaround to allow self-signed certificates seems dubious.

**Comment by twisted1919** [comment]
I don't remember the exact reason for why that code is like so, i am sure i had good reasons (or not).  
I'll update it as soon as i get a chance, otherwise, feel free to make a pull request with the code commented out.
