### ISSUE TITLE
Update SDK to meet new mailwizz feature

### ISSUE THREAD

**Issue by thangtx** [twisted1919/mailwizz-php-sdk#9]
Please update SDK, example to meet new mailwizz feature like Preheader,Actions against subscribers upon campaign open, Change subscriber custom field value upon campaign open, Max. subscribers, Randomize subscribers, Send this campaign only to subscribers that have opened or have not opened a certain campaign...

Thanks

**Comment by simplexx** [comment]
Dito, an updated version of this api would be great!

**Comment by marioffmarques** [comment]
Hello @twisted1919 Hope you are doing fine.
I didn't find any commit (or any example) to solve the issue mentioned above about setting "Actions against subscribers upon campaign open".

Could you kindly inform me about what is the property name we can use to set "Actions against subscribers upon campaign open" when creating a Campaign through the mailwizz api ?

Thanks
